# Generated by Django 5.1.3 on 2024-11-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('enrollment_no', models.BigIntegerField()),
                ('age', models.IntegerField()),
                ('class_level', models.IntegerField()),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
