# Generated by Django 5.1.3 on 2024-12-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_imgupload_alter_student_data_enrollment_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='imgupload',
            new_name='img_upload',
        ),
    ]
